import type { Metadata } from "next";
import { FaGithub } from "react-icons/fa";

import Header from "@/components/header";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Портфолио",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Header />
        {children}

        <div className="Media">
          <div className="Media-Line"></div>
          <div className="Media-Links">
            <a href="https://github.com/iewher" target="_about">
              <FaGithub />
            </a>
          </div>
        </div>
      </body>
    </html>
  );
}
